services:
  db:
    image: postgres:latest
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PWD}
      - POSTGRES_DB=old_stars_db
