version: "3.9"
services:

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PWD}
      - POSTGRES_DB=old_stars_db

  backend:
    image: old_stars_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./certs:/certs
    depends_on:
      - db
    environment:
      - RUST_BACKTRACE=1
      - DATABASE_URL=postgres://${PG_USER}:${PG_PWD}@db/old_stars_db
        #- ROCKET_DATABASES={db={url="postgres://${PG_USER}:${PG_PWD}@db/old_stars_db"}}
      - ROCKET_DATABASES='{db={url="postgres://${PG_USER}:${PG_PWD}@db/old_stars_db"}}'
      - ROCKET_ADDRESS=0.0.0.0
      - ROCKET_PORT=443
      - CERT_CHAIN=${CERT_CHAIN}
      - PRIVATE_KEY=${PRIVATE_KEY}
    command: bash -c "bash ./wait_for_it.sh db:5432 -- /usr/local/bin/backend"
