services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PWD}
      - POSTGRES_DB=old_stars_db

  backend:
    image: ghcr.io/niilz/old_stars_backend:main
    ports:
      - 80:8000
      - 443:1443
    volumes:
      - ./certs:/certs
      - ./logs:/logs
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://${PG_USER}:${PG_PWD}@db/old_stars_db
      - ROCKET_ADDRESS=0.0.0.0
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PWD=${ADMIN_PWD}
      - CLUB_USER=${CLUB_USER}
      - CLUB_PWD=${CLUB_PWD}
      - CERT_CHAIN=${CERT_CHAIN}
      - PRIVATE_KEY=${PRIVATE_KEY}
    command: bash -c "env > /logs/dc.env.dump && ./wait_for_it.sh db:5432 -- && /usr/local/bin/configurator -u ${ADMIN_USER} -p ${ADMIN_PWD} -r admin && /usr/local/bin/configurator -u ${CLUB_USER} -p ${CLUB_PWD} -r club && /usr/local/bin/backend"
