version: "3.9"
services:
  backend:
    build: ./backend
    image: old-stars-backend
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PWD}
      - POSTGRES_DB=old_stars_db



