[package]
name = "backend"
version = "0.1.0"
authors = ["nilSinger <niilz@outlook.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.10"
rocket_contrib = { version = "0.4.10", features = ["diesel_postgres_pool"] }
rocket_cors = "0.5.1"
diesel = { version = "1.4.4", features = ["postgres"] }
dotenv = "0.15"
diesel_migrations = "1.4"
serde = { version = "1", features = ["derive"] }
rand_core = {version = "0.6", features = ["std"] }
argon2 = "0.2"

[[bin]]
name = "backend"

