name: Build & Deploy old-stars-backend

on: [push]

env:
  CARGO_TERM_COLOR: always
defaults:
  run:
    working-directory: backend
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Backend
        run: cargo build --verbose
