name: Build and Deploy old-stars-backend

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Check out backend-code
        uses: actions/checkout@v3
      - name: Build
        run: cargo check --verbose
